name: setup
description: Setup up repository
inputs:
  python-version:
    description: Python version to setup
    required: false
    default: "3.14"
  uv-version:
    description: UV version to setup
    required: false

runs:
  using: composite
  steps:
    - name: Setup uv
      uses: astral-sh/setup-uv@v7
      with:
        version: ${{ inputs.uv-version }}
        python-version: ${{ inputs.python-version }}

    - uses: actions/cache@v4
      name: Define a cache for the virtual environment based on the dependencies lock file
      with:
        path: ./.venv
        key: venv-${{ runner.os }}-${{ runner.arch }}-${{ inputs.python-version }}-${{ hashFiles('**/uv.lock') }}