# Stub generated by pydantic_views.stubgen. Includes regular types, Pydantic models,
# declared views, and views generated at runtime by the builders.

from datetime import datetime
from enum import StrEnum
from typing import Literal

from pydantic import BaseModel

from pydantic_views import View
from pydantic_views.builder import Preset

InternalCreatePreset: Preset
InternalUpdatePreset: Preset
var_int: int
var_str: str

class AddressType(StrEnum):
    HOME = "home"
    WORK = "work"
    OTHER = "other"

    @classmethod
    def from_string(cls, type_str: str) -> AddressType: ...
    @staticmethod
    def is_valid_type(type_str: str) -> bool: ...
    def __str__(self) -> str: ...

class Address(BaseModel):
    type: AddressType
    street: str
    number: int
    zip_code: str
    notes: str | None

    def __init__(
        self, *, type: AddressType, street: str, number: int, zip_code: str, notes: str | None = ...
    ) -> None: ...
    @property
    def full_address(self) -> str: ...
    @full_address.setter
    def full_address(self, value: str) -> None: ...
    @classmethod
    def from_string(cls, address_str: str) -> Address: ...
    @staticmethod
    def is_valid_zip(zip_code: str) -> bool: ...

class Role(BaseModel):
    class RoleType(StrEnum):
        ADMIN = "admin"
        USER = "user"
        GUEST = "guest"

    type: Role.RoleType
    name: str
    level: int

    def __init__(self, *, type: Role.RoleType, name: str, level: int) -> None: ...

class User(BaseModel):
    name: str
    kind: Literal["person", "bot"]
    id: int
    created_at: datetime
    api_key: str
    password: str
    invite_code: str | None
    score: int
    internal_flags: int
    primary_address: Address
    addresses: list[Address]
    roles: dict[str, Role]

    def __init__(
        self,
        *,
        name: str,
        kind: Literal["person", "bot"] = ...,
        id: int,
        created_at: datetime,
        api_key: str,
        password: str,
        invite_code: str | None = ...,
        score: int = ...,
        internal_flags: int = ...,
        primary_address: Address,
        addresses: list[Address] = ...,
        roles: dict[str, Role] = ...,
    ) -> None: ...
    @property
    def display_name(self) -> str: ...

class UserCreate(View[User]):
    name: str
    kind: Literal["person", "bot"]
    password: str
    invite_code: str
    score: int
    primary_address: AddressCreate
    addresses: list[AddressCreate]
    roles: dict[str, RoleCreate]

    def __init__(
        self,
        *,
        name: str,
        kind: Literal["person", "bot"] = ...,
        password: str,
        invite_code: str = ...,
        score: int = ...,
        primary_address: AddressCreate,
        addresses: list[AddressCreate] = ...,
        roles: dict[str, RoleCreate] = ...,
    ) -> None: ...

class UserCreateResult(View[User]):
    name: str
    kind: Literal["person", "bot"]
    id: int
    created_at: datetime
    api_key: str
    score: int
    primary_address: AddressCreateResult
    addresses: list[AddressCreateResult]
    roles: dict[str, RoleCreateResult]
    display_name: str

    def __init__(
        self,
        *,
        name: str,
        kind: Literal["person", "bot"] = ...,
        id: int,
        created_at: datetime,
        api_key: str,
        score: int = ...,
        primary_address: AddressCreateResult,
        addresses: list[AddressCreateResult] = ...,
        roles: dict[str, RoleCreateResult] = ...,
        display_name: str = ...,
    ) -> None: ...

class UserUpdate(View[User]):
    name: str
    kind: Literal["person", "bot"]
    password: str
    primary_address: AddressUpdate
    addresses: list[AddressUpdate]
    roles: dict[str, RoleUpdate]

    def __init__(
        self,
        *,
        name: str = ...,
        kind: Literal["person", "bot"] = ...,
        password: str = ...,
        primary_address: AddressUpdate = ...,
        addresses: list[AddressUpdate] = ...,
        roles: dict[str, RoleUpdate] = ...,
    ) -> None: ...

class UserLoad(View[User]):
    name: str
    kind: Literal["person", "bot"]
    id: int
    created_at: datetime
    score: int
    primary_address: AddressLoad
    addresses: list[AddressLoad]
    roles: dict[str, RoleLoad]
    display_name: str

    def __init__(
        self,
        *,
        name: str,
        kind: Literal["person", "bot"] = ...,
        id: int,
        created_at: datetime,
        score: int = ...,
        primary_address: AddressLoad,
        addresses: list[AddressLoad] = ...,
        roles: dict[str, RoleLoad] = ...,
        display_name: str = ...,
    ) -> None: ...

class UserPatch(View[User]):
    name: str | None
    kind: Literal["person", "bot"]
    password: str | None
    primary_address: AddressPatch | None
    addresses: list[AddressPatch] | None
    roles: dict[str, RolePatch | None] | None

    def __init__(
        self,
        *,
        name: str | None = ...,
        kind: Literal["person", "bot"] = ...,
        password: str | None = ...,
        primary_address: AddressPatch | None = ...,
        addresses: list[AddressPatch] | None = ...,
        roles: dict[str, RolePatch | None] | None = ...,
    ) -> None: ...

class UserSignup(View[User]):
    accept_terms: bool
    referral_code: str | None
    name: str
    kind: Literal["person", "bot"]
    password: str
    invite_code: str
    score: int
    primary_address: AddressSignup
    addresses: list[AddressSignup]
    roles: dict[str, RoleSignup]

    def __init__(
        self,
        *,
        accept_terms: bool,
        referral_code: str | None = ...,
        name: str,
        kind: Literal["person", "bot"] = ...,
        password: str,
        invite_code: str = ...,
        score: int = ...,
        primary_address: AddressSignup,
        addresses: list[AddressSignup] = ...,
        roles: dict[str, RoleSignup] = ...,
    ) -> None: ...

class Account(BaseModel):
    id: int
    username: str
    password: str

    def __init__(self, *, id: int, username: str, password: str) -> None: ...

class AccountCreate(View[Account]):
    accept_terms: bool
    captcha: str | None
    username: str
    password: str

    def __init__(self, *, accept_terms: bool, captcha: str | None = ..., username: str, password: str) -> None: ...

class AccountLoad(View[Account]):
    id: int
    username: str

    def __init__(self, *, id: int, username: str) -> None: ...

class AddressCreate(View[Address]):
    type: AddressType
    street: str
    number: int
    notes: str

    def __init__(self, *, type: AddressType, street: str, number: int, notes: str = ...) -> None: ...

class AddressCreateResult(View[Address]):
    type: AddressType
    street: str
    number: int
    zip_code: str

    def __init__(self, *, type: AddressType, street: str, number: int, zip_code: str) -> None: ...

class AddressLoad(View[Address]):
    type: AddressType
    street: str
    number: int
    zip_code: str

    def __init__(self, *, type: AddressType, street: str, number: int, zip_code: str) -> None: ...

class AddressPatch(View[Address]):
    type: AddressType | None
    street: str | None
    number: int | None
    notes: str | None

    def __init__(
        self,
        *,
        type: AddressType | None = ...,
        street: str | None = ...,
        number: int | None = ...,
        notes: str | None = ...,
    ) -> None: ...

class AddressSignup(View[Address]):
    type: AddressType
    street: str
    number: int
    notes: str

    def __init__(self, *, type: AddressType, street: str, number: int, notes: str = ...) -> None: ...

class AddressUpdate(View[Address]):
    type: AddressType
    street: str
    number: int
    notes: str | None

    def __init__(
        self, *, type: AddressType = ..., street: str = ..., number: int = ..., notes: str | None = ...
    ) -> None: ...

class RoleCreate(View[Role]):
    type: Role.RoleType
    name: str

    def __init__(self, *, type: Role.RoleType, name: str) -> None: ...

class RoleCreateResult(View[Role]):
    type: Role.RoleType
    name: str
    level: int

    def __init__(self, *, type: Role.RoleType, name: str, level: int) -> None: ...

class RoleLoad(View[Role]):
    type: Role.RoleType
    name: str
    level: int

    def __init__(self, *, type: Role.RoleType, name: str, level: int) -> None: ...

class RolePatch(View[Role]):
    type: Role.RoleType | None
    name: str | None

    def __init__(self, *, type: Role.RoleType | None = ..., name: str | None = ...) -> None: ...

class RoleSignup(View[Role]):
    type: Role.RoleType
    name: str

    def __init__(self, *, type: Role.RoleType, name: str) -> None: ...

class RoleUpdate(View[Role]):
    type: Role.RoleType
    name: str

    def __init__(self, *, type: Role.RoleType = ..., name: str = ...) -> None: ...

def get_user_display_name(user: User) -> str: ...
