# Illustrative output: this is what the pydantic_views.mypy plugin makes mypy "see" for each
# view. Nested-model fields use the generated nested views (e.g. AddressLoad), exactly as the
# runtime builder produces them. Generated by examples/generate_stubs.py; not an importable stub.

from typing import Any, Literal

from pydantic_views import View

class AccountCreate(View[Account]):
    username: str
    password: str
    accept_terms: bool
    captcha: str | None
    def __init__(self, *, username: str, password: str, accept_terms: bool, captcha: str | None = ...) -> None: ...


class AccountLoad(View[Account]):
    id: int
    username: str
    def __init__(self, *, id: int, username: str) -> None: ...


class AddressCreate(View[Address]):
    street: str
    number: int
    notes: str | None
    def __init__(self, *, street: str, number: int, notes: str | None = ...) -> None: ...


class AddressCreateResult(View[Address]):
    street: str
    number: int
    zip_code: str
    def __init__(self, *, street: str, number: int, zip_code: str) -> None: ...


class AddressLoad(View[Address]):
    street: str
    number: int
    zip_code: str
    def __init__(self, *, street: str, number: int, zip_code: str) -> None: ...


class AddressPatch(View[Address]):
    street: str | None
    number: int | None
    notes: str | None
    def __init__(self, *, street: str | None = ..., number: int | None = ..., notes: str | None = ...) -> None: ...


class AddressSignup(View[Address]):
    street: str
    number: int
    notes: str | None
    def __init__(self, *, street: str, number: int, notes: str | None = ...) -> None: ...


class AddressUpdate(View[Address]):
    street: str
    number: int
    notes: str | None
    def __init__(self, *, street: str = ..., number: int = ..., notes: str | None = ...) -> None: ...


class RoleCreate(View[Role]):
    name: str
    def __init__(self, *, name: str) -> None: ...


class RoleCreateResult(View[Role]):
    name: str
    level: int
    def __init__(self, *, name: str, level: int) -> None: ...


class RoleLoad(View[Role]):
    name: str
    level: int
    def __init__(self, *, name: str, level: int) -> None: ...


class RolePatch(View[Role]):
    name: str | None
    def __init__(self, *, name: str | None = ...) -> None: ...


class RoleSignup(View[Role]):
    name: str
    def __init__(self, *, name: str) -> None: ...


class RoleUpdate(View[Role]):
    name: str
    def __init__(self, *, name: str = ...) -> None: ...


class UserCreate(View[User]):
    name: str
    kind: Literal['person'] | Literal['bot']
    password: str
    invite_code: str | None
    score: int
    primary_address: AddressCreate
    addresses: list[AddressCreate]
    roles: dict[str, RoleCreate]
    def __init__(self, *, name: str, kind: Literal['person'] | Literal['bot'] = ..., password: str, invite_code: str | None = ..., score: int = ..., primary_address: AddressCreate, addresses: list[AddressCreate] = ..., roles: dict[str, RoleCreate] = ...) -> None: ...


class UserCreateResult(View[User]):
    name: str
    kind: Literal['person'] | Literal['bot']
    id: int
    created_at: datetime
    api_key: str
    score: int
    primary_address: AddressCreateResult
    addresses: list[AddressCreateResult]
    roles: dict[str, RoleCreateResult]
    display_name: str
    def __init__(self, *, name: str, kind: Literal['person'] | Literal['bot'] = ..., id: int, created_at: datetime, api_key: str, score: int = ..., primary_address: AddressCreateResult, addresses: list[AddressCreateResult] = ..., roles: dict[str, RoleCreateResult] = ..., display_name: str = ...) -> None: ...


class UserLoad(View[User]):
    name: str
    kind: Literal['person'] | Literal['bot']
    id: int
    created_at: datetime
    score: int
    primary_address: AddressLoad
    addresses: list[AddressLoad]
    roles: dict[str, RoleLoad]
    display_name: str
    def __init__(self, *, name: str, kind: Literal['person'] | Literal['bot'] = ..., id: int, created_at: datetime, score: int = ..., primary_address: AddressLoad, addresses: list[AddressLoad] = ..., roles: dict[str, RoleLoad] = ..., display_name: str = ...) -> None: ...


class UserPatch(View[User]):
    name: str | None
    kind: Literal['person'] | Literal['bot'] | None
    password: str | None
    primary_address: AddressPatch | None
    addresses: list[AddressPatch] | None
    roles: dict[str, RolePatch] | None
    def __init__(self, *, name: str | None = ..., kind: Literal['person'] | Literal['bot'] | None = ..., password: str | None = ..., primary_address: AddressPatch | None = ..., addresses: list[AddressPatch] | None = ..., roles: dict[str, RolePatch] | None = ...) -> None: ...


class UserSignup(View[User]):
    name: str
    kind: Literal['person'] | Literal['bot']
    password: str
    invite_code: str | None
    score: int
    primary_address: AddressSignup
    addresses: list[AddressSignup]
    roles: dict[str, RoleSignup]
    accept_terms: bool
    referral_code: str | None
    def __init__(self, *, name: str, kind: Literal['person'] | Literal['bot'] = ..., password: str, invite_code: str | None = ..., score: int = ..., primary_address: AddressSignup, addresses: list[AddressSignup] = ..., roles: dict[str, RoleSignup] = ..., accept_terms: bool, referral_code: str | None = ...) -> None: ...


class UserUpdate(View[User]):
    name: str
    kind: Literal['person'] | Literal['bot']
    password: str
    primary_address: AddressUpdate
    addresses: list[AddressUpdate]
    roles: dict[str, RoleUpdate]
    def __init__(self, *, name: str = ..., kind: Literal['person'] | Literal['bot'] = ..., password: str = ..., primary_address: AddressUpdate = ..., addresses: list[AddressUpdate] = ..., roles: dict[str, RoleUpdate] = ...) -> None: ...
