name: Common get version

on:
  workflow_call:
    inputs:
      ref:
        description: "Base branch reference"
        required: false
        type: string

      level:
        description: "Release level"
        required: false
        type: string
        default: none

    outputs:
      version:
        description: "Version"
        value: ${{ jobs.get_version.outputs.version }}
      version-no-build:
        description: "Version with no build part"
        value: ${{ jobs.get_version.outputs.version-no-build }}
      release-major:
        description: "Release major granularity"
        value: ${{ jobs.get_version.outputs.release-major }}
      release-minor:
        description: "Release minor granularity"
        value: ${{ jobs.get_version.outputs.release-minor }}
      release-patch:
        description: "Release patch granularity"
        value: ${{ jobs.get_version.outputs.release-patch }}
      release-ref:
        description: "Release branch"
        value: release/${{ jobs.get_version.outputs.release-minor }}
      part-major:
        description: "Major part of release version"
        value: ${{ jobs.get_version.outputs.part-major }}
      part-minor:
        description: "Minor part of release version"
        value: ${{ jobs.get_version.outputs.part-minor }}
      part-patch:
        description: "Patch part of release version"
        value: ${{ jobs.get_version.outputs.part-patch }}
      part-prerelease-type:
        description: "Prerelease type part of release version"
        value: ${{ jobs.get_version.outputs.part-prerelease-type }}
      part-prerelease-number:
        description: "Prerelease number part of release version"
        value: ${{ jobs.get_version.outputs.part-prerelease-number }}
      part-build:
        description: "Build part of release version"
        value: ${{ jobs.get_version.outputs.part-build }}
      is-prerelease:
        description: "Whether is a prerelease version"
        value: ${{ jobs.get_version.outputs.is-prerelease }}

permissions:
  contents: read

jobs:
  get_version:
    name: Get version
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    outputs:
      current-version: ${{ steps.define-version.outputs.current-version }}
      version: ${{ steps.define-version.outputs.version }}
      version-no-build: ${{ steps.define-version.outputs.version-no-build }}
      release-major: ${{ steps.define-version.outputs.release-major }}
      release-minor: ${{ steps.define-version.outputs.release-minor }}
      release-patch: ${{ steps.define-version.outputs.release-patch }}
      part-major: ${{ steps.define-version.outputs.part-major }}
      part-minor: ${{ steps.define-version.outputs.part-minor }}
      part-patch: ${{ steps.define-version.outputs.part-patch }}
      part-prerelease-type: ${{ steps.define-version.outputs.part-prerelease-type }}
      part-prerelease-number: ${{ steps.define-version.outputs.part-prerelease-number }}
      part-build: ${{ steps.define-version.outputs.part-build }}
      is-prerelease: ${{ steps.define-version.outputs.is-prerelease }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ inputs.ref }}
          
      - uses: ./.github/actions/setup-repo

      - uses: ./.github/actions/versioning
        id: define-version
        with:
          level: ${{ inputs.level }}
